Merge remote-tracking branch 'origin/master'
# Conflicts:
#	.github/workflows/ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,6 +101,7 @@ jobs:
 #          docker push vvo15/my-image-server1
   deploy:
     runs-on: ubuntu-latest
+    needs: docker
 
     steps:
       - name: Checkout code
@@ -111,8 +112,17 @@ jobs:
           mkdir -p $HOME/.yandex/bin
           curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
           echo "$HOME/.yandex/bin" >> $GITHUB_PATH
-          echo "Yandex Cloud CLI installed at: $HOME/.yandex/bin/yc"
+          
+          # Проверка установки
+          echo "Checking Yandex Cloud CLI installation..."
           ls -la $HOME/.yandex/bin
+          if [ -f "$HOME/.yandex/bin/yc" ]; then
+            echo "Yandex Cloud CLI installed successfully."
+            $HOME/.yandex/bin/yc version  # Вывод версии для проверки
+          else
+            echo "Yandex Cloud CLI not found!"
+            exit 1
+          fi
 
       - name: Authenticate with Yandex Cloud
         run: |
